# Generated by Django 4.2.5 on 2024-05-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('Flight_No', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Airline', models.CharField(max_length=20)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
