# Generated by Django 4.2.5 on 2024-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Price',
            field=models.CharField(max_length=20),
        ),
    ]
